"""Final structure for OrderProduct snapshots

Revision ID: 2c2d1273c417
Revises: 
Create Date: 2026-05-15 03:59:50.585957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2d1273c417'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_customer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['customer_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_customer_id_fkey'), 'user', ['customer_id'], ['user_id'], ondelete='SET NULL')

    # ### end Alembic commands ###
